# Configuration de base du build
[build]
  # Ces valeurs doivent correspondre à votre configuration de déploiement
  command = "npm run build"
  publish = "dist"

# La règle de réécriture magique qui résout le problème du 404 !
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200